### PR TITLE
Path rewrite support

### PR DESCRIPTION
**Pull request by uroybd**
Complements https://github.com/oleeskild/obsidian-digital-garden/pull/239

### CODE REVIEW

**Comment by oleeskild** [comment]
Lovely 🙌 Did some testing, and I've found a bug.  Not sure what causes it. Tried to add three different notes to the same path "dg-path":"foo/bar/". This results in only one of the notes being shown in that folder.

**Comment by uroybd** [comment]
> Lovely 🙌 Did some testing, and I've found a bug.  Not sure what causes it. Tried to add three different notes to the same path "dg-path":"foo/bar/". This results in only one of the notes being shown in that folder.

`dg-path` should be complete path, with filename and extension. I think we should mention it in docs.

**Comment by Lisandra-dev** [comment]
Why the need of the extension? At last, only markdown file can have front matter.

**Comment by uroybd** [comment]
> Why the need of the extension? At last, only markdown file can have front matter. 
> 

The need of extension is only for manual override.

For example, if you want to put only `Foo/Bar/Note.md` to `Buzz/Note.md`, you will have to put tje later as the `dg-path` in the frontmatter.

However, if you want to map everything from `Foo/Bar` to `Buzz` (which is the main usecase), add `Foo/Bar:Buzz` in the path rewrite settings in the plugins settings.

A larger example, here's the mapping I'm using to produce the filetree of https://hermitage.utsob.me

```
Personal/Journal/The Supposed Last Year of My Life:Journal
Personal/Journal:Journal
Personal/Musings:Musings
Personal/Reading:Reading
Personal/Writings:Writings
Entities/Concept:Entities/Concepts
Entities/Object:Entities/Objects
Entities/Technical Draft:Entities/Technical Drafts
Entities/Person:Entities/People
```

**Comment by Lisandra-dev** [comment]
So if I understand, I can "rewrite" a folder path to another folder path ? For example, mapping `10. Project` to `Compendium` with `10. Project:Compendium` ? So the settings allow to "rename" folder path to another ? 
I think I will more use the `dg-path` because I don't use the same tree for my blog and Obsidian. 

ie 
`10. Project/Project/character.md` can be in `Compendium/characters` and `10. Project/Project/univers.md` can be in `Projects/Project`

**Pull request merged**
