### PR TITLE
Hide dataview variable

### PR DESCRIPTION
**Pull request by uroybd**
According to [DataView docs](https://blacksmithgu.github.io/obsidian-dataview/annotation/add-metadata/#inline-fields), users should be able to add DataView value with hidden keys with the following format:

```md
This will not show the (longKeyIDontNeedWhenReading:: key).
```

Which will show as the following in the Reader Mode:

```md
This will not show the key.
```

This PR implements just that for the notes published.

### CODE REVIEW

**Comment by uroybd** [comment]
@oleeskild let me know your opinion whenever you're free.

**Comment by oleeskild** [comment]
Great! Thank you, I'll have a look some time this week.
Quick question: do you have an eslint or something similar in your version of the project? It seems your formatting changes are consistent across PRs. I haven't bothered to make one yet, but seeing as more and more people are contributing, it would be nice if the PRs didn't have too much formatting changes. Don't worry if you don't have one, I'll just generate one myself 😄

**Comment by uroybd** [comment]
> Great! Thank you, I'll have a look some time this week.
> Quick question: do you have an eslint or something similar in your version of the project? It seems your formatting changes are consistent across PRs. I haven't bothered to make one yet, but seeing as more and more people are contributing, it would be nice if the PRs didn't have too much formatting changes. Don't worry if you don't have one, I'll just generate one myself 😄 

Please generate one. Probably, my default fallback settings is being used.

**Comment by uroybd** [comment]
@oleeskild take a look on this and #59

We can have a hefty update!

**Pull request merged**
