### PR TITLE
Note Icon visualization

### PR DESCRIPTION
**Pull request by uroybd**
Complements https://github.com/oleeskild/obsidian-digital-garden/pull/189

Customizations are easy.

An user can add any maturity level just by adding custom CSS and image assets.

### CODE REVIEW

**Comment by uroybd** [comment]
I've tested this against a test site locally. Working as expected.

**Comment by uroybd** [comment]
@oleeskild I've added the icons from my site since I couldn't find a good set of svg icons for this usecase. I've no problem people using them. However, they are very amateurishly designed. Let me know if you have an alternative with no licencing issues.

**Comment by uroybd** [comment]
@oleeskild I've resolved the conflicts. Merge this and it's companion whenever you can review the code.

**Comment by oleeskild** [comment]
Done! It was a good idea to generalize this into note icons instead of the special maturity case. You've really been on a role lately. I haven't had a time the last months to work on this as much as I would like to, so you creating PRs for all of these feature lately is really appreciated!

**Comment by uroybd** [comment]
Btw, whenever you can, do an AMA on reddit. I think, we can learn a lot about how the users are using it, what they want etc.

**Comment by uroybd** [comment]
The ideal way to change the default icons is by adding the svgs in the img folder and setting the appropriate css vars in body in custom css file:

```css
body {
  --note-icon-1: url(/img/tree-1.svg);
  --note-icon-2: url(/img/tree-2.svg);
  --note-icon-3: url(/img/tree-3.svg);
  --note-icon-fallback: url(/img/default-note-icon.svg);}
}
```

This way, changes won't be overridden in theme update. 

To add new icons, let's say, for 'stone', add a snippet like this (and add the relevant svg) in custom css:

```css
body.title-note-icon .cm-s-obsidian > header > h1[data-note-icon="stone"]::before,body.filetree-note-icon .filename[data-note-icon="stone"]::before,body.links-note-icon .internal-link[data-note-icon="stone"]::before {
  background-image: url(/img/stone.svg);
}
```

**Comment by oleeskild** [comment]
They won't get overwridden by theme updates, as I've added them to the list "filesToAdd" in the [plugin-info.json](https://github.com/oleeskild/digitalgarden/blob/main/plugin-info.json) file. The files in here only gets added if they currently don't exist.

Having said that, the way you've described it here is probably a more "correct" way to do it. And it also allows users to easily add new icons. Updating the docs right away.

**Pull request merged**
